version: '3'

volumes:
  db_data:
  gems_web:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gems_web:/usr/local/bundle
    depends_on:
      - db
      - sidekiq

  sidekiq:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - '.:/app'
    depends_on:
      - 'db'
      - 'redis'

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    restart: always
    image: postgres:13.7
    ports:
      - "5953:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_development
      POSTGRES_HOST_AUTH_METHOD: trust
