default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: db

development:
  <<: *default
  database: myapp_development
  username: postgres
  password: 

test:
  <<: *default
  database: myapp_test
  username: postgres
  password: 

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DB'] %>
  host:     <%= ENV['PRODUCTION_HOST'] %>
  username: <%= ENV['PRODUCTION_USERNAME'] %>
  password: <%= ENV['PRODUCTION_PASSWORD'] %>

