default: &default
  adapter: postgresql
  encoding: unicode
  host: containers-us-west-106.railway.app
  port: 5953
  database: railway
  username: postgres
  password: X0I0RqHfa7LPZB1IEBdl

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default