default: &default
  adapter: postgresql
  encoding: unicode
  host: containers-us-west-106.railway.app
  port: 5953
  database: railway
  username: postgres
  password: X0I0RqHfa7LPZB1IEBdl

development:
  <<: *default
  database: myapp_development
  host: db
  username: postgres
  password:
  port: 5432

test:
  <<: *default

production:
  <<: *default

