default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['host'] %>
  port: <%= ENV['port'] %>
  database: <%= ENV['database'] %>
  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: railway
  username: postgres
  password: X0I0RqHfa7LPZB1IEBdl
  host: containers-us-west-106.railway.app
  port: 5953