default: &default
  adapter: postgresql
  encoding: unicode
  database: railway
  host: containers-us-west-106.railway.app
  username: postgres
  password: X0I0RqHfa7LPZB1IEBdl
  port: 5953

development:
  <<: *default
  pool: 5
  database: myapp_development
  host: db
  username: postgres
  password:

test:
  database: myapp_test
  <<: *default

production:
  <<: *default

