default: &default
  adapter: postgresql
  encoding: unicode
  host: containers-us-west-106.railway.app
  port: 5953
  database: railway
  username: postgres
  password: X0I0RqHfa7LPZB1IEBdl


development:
  <<: *default
#  database: myapp_development
#  username: postgres
#  password: 
#  host: db

test:
  <<: *default
#  database: myapp_test
# username: postgres
#  password: 

production:
  <<: *default


